require("modules.autostart")
require("modules.bindings")
require("modules.decorations")
require("modules.env")
require("modules.inputs")
require("modules.misc")
require("modules.monitors")
require("modules.rules")
require("modules.plugins")

