# Plugins Declaration
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'Morantron/tmux-fingers'
set -g @plugin 'nhdaly/tmux-better-mouse-mode'
set -g @plugin 'alexekdahl/tmux-compile'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'azorng/tmux-smooth-scroll'
set -g @plugin 'alexwforsythe/tmux-which-key'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'lost-melody/tmux-command-palette'
set -g @plugin 'omerxx/tmux-floax'
set -g @plugin 'omerxx/tmux-sessionx'
# Plugin Options

## tmux-fingers
bind -n M-f run -b "#{@fingers-cli} start #{pane_id}"
bind u run -b "#{@fingers-cli} start #{pane_id} --patterns url"
