#!/usr/bin/env bash

# Retrieve the current state of animations
ANIMATIONS_ENABLED=$(hyprctl getoption animations:enabled | awk 'NR==2{print $2}')

if [ "$ANIMATIONS_ENABLED" = "1" ]; then
    # Enable performance mode
    hyprctl --batch "
        keyword animations:enabled 0
        keyword decoration:drop_shadow 0
        keyword decoration:blur:enabled 0
        keyword general:gaps_in 0
        keyword general:gaps_out 0
        keyword general:border_size 1
        keyword decoration:rounding 0
    "

    # Terminate Waybar if running
    pkill waybar

    notify-send "Performance Mode Enabled"
else
    # Reload Hyprland configuration to restore normal mode settings
    hyprctl reload

    # Restart Waybar
    waybar &

    notify-send "Performance Mode Disabled"
fi
